<?php if (count($this->users)): ?>
	<table>
		<tr>
			<th>ID</th>
			<th>Username</th>
			<th>Email</th>
			<th>Activated</th>
			<th>Actions</th>
		</tr>
		<?php foreach ($this->users as $user): ?>
			<tr>
				<td><?php echo $user->id; ?></td>
				<td>
					<a href="<?php echo $this->url(array(
						'controller' => 'users',
						'action' => 'view',
						'id' => $user->id
					)); ?>"><?php echo $user->username; ?></a>
				</td>
				<td><?php echo $user->email; ?></td>
				<td><?php echo $user->activated; ?></td>
				<td>
					<a href="<?php echo $this->url(array(
						'controller' => 'users',
						'action' => 'edit',
						'id' => $user->id
					)); ?>">Edit</a>
					<a href="<?php echo $this->url(array(
						'controller' => 'users',
						'action' => 'delete',
						'id' => $user->id
					)); ?>">Delete</a>
				</td>
			</tr>
		<?php endforeach ?>
	</table>
	
<?php else: ?>
	<p>Пользователей пока нет.</p>
<?php endif ?>

<a href="<?php echo $this->url(array(
	'controller' => 'users',
	'action' => 'add'
)); ?>">Добавить нового пользователя</a>